### ISSUE TITLE
GNSS Metadata

### ISSUE THREAD

**Issue by Hughwyn** [Esri/collector-tools#71]
Hello,

Is there anyway to set up a feature class so the LLQ message from the NMEA stream can be stored? I have set local coordinates and a geoid in the receiver and Im trying to get this GNSS metadata stored so I do not have to do a coordinate transformation post processing.

Thanks

Hugh

**Comment by Kevin-GIS** [comment]
Hi @Hughwyn 

Can you please explain what the LLQ string is? I am familiar with the NMEA standard, but not regarding that particular string. My research tells me that's a proprietary string for Leica receivers. Is that the case?

Are you using a Leica receiver?

Because you setup the receiver to use local coordinates, are these the coordinates that are contained within that string? As opposed to the coordinates stored in GGA which aren't localized?

To answer your question, in Collector the metadata is designed to store certain information from specific NMEA strings according the NMEA 0183 Standard, which are supported across many different GNSS receivers. Unfortunately this functionality cannot be customized.

**Comment by Hughwyn** [comment]
Hi Kevin

Thank you for your prompt response.

Yes I am using a Leica Receiver.

Yes the localised coordinates are stored in the LLQ string as per the screenshot below.
[cid:image001.png@01D4C91D.4FFECC00]
Is there any way to store the metadata from this LLQ message (specially Grid Easting, Grid Northing and Height)? Perhaps via another script?

Kind Regards


Hugh Wyn-Harris
BSurv, ANZIS
Surveyor

[cid:image004.png@01D4C91D.50020050]
[http://press.linkedin.com/display-media/313/2]<https://www.linkedin.com/company/envivo-ltd---planning-surveying-engineering/?originalSubdomain=nz>
W: envivo.co.nz<http://www.envivo.co.nz/>
P: 09 630 9512 | DDI: 09 638 2636

**Comment by Kevin-GIS** [comment]
Hi @Hughwyn 

I apologize for the delay. 

Thank you for that information.

Unfortunately no there isn't a way to store metadata for that string type in Collector. Even if the scripts were modified to include it, under the hood the app is not looking for that string to parse it. Therefore it's not supported.
