### ISSUE TITLE
ProjectZ runs, but doesn't actually convert elevations

### ISSUE THREAD

**Issue by aaronpaBMI** [Esri/collector-tools#77]
I have been trying to figure out if there is some kind of issue with my inputs for this tool. I am able to run it successfully, but the output Z value has not been changed. The output values are exactly the same as the input values. I have attached an image of the inputs. Maybe there is something that I'm not doing correctly that you'll be able to see. I am using ArcGIS Pro 2.3.2. Any insight as to what is happening?

Thanks!

![image](https://user-images.githubusercontent.com/52046424/59866388-0eb6b600-9351-11e9-9619-798cffa595a0.png)

**Comment by michellejakson** [comment]
I have the same issue.  I can run the tool successfully; however, my z value does not change.

**Comment by Danik-B** [comment]
I'm getting the same result as well.  No change in z values.

**Comment by Kevin-GIS** [comment]
@aaronpaBMI @michellejakson @Danik-B 

Thank you for the feedback. I just wanted to confirm the 'Z values' you're referring to. Are you referring to the values in the 'Altitude' field or in the POINT_Z field?

What are the datums (horizontal and vertical) you're transforming between?

Thanks

**Comment by LowellMA-stormwater** [comment]
I have the same issue - I am collecting the data in Massachusetts using Collector with a Leica receiver set to collect ellipsoidal height and save it to the 'Altitude' field on my test layer. In Pro (latest update 2.4.2), I project the WGS84 coordinates from my feature layer to NAD1983 (2011) so that I can then run ProjectZ with the input coordinate systems each set to NAD1983 (2011) - choosing the ellipsoidal based option for the vertical coordinate system. I then run the tool, but the POINT_Z field created contains the exact same ellipsoidal heights (untransformed) that I put in.

**Comment by LowellMA-stormwater** [comment]
I encountered this issue as well and after reading the documentation more closely I realized it is likely because I have not installed the Coordinate Systems Data files from MyEsri. It might be helpful to add an idiot-proof error trap on this (for folks like me) to prevent use of the tool if the specified vertical transformation file is unavailable (and reference the resolution as well), rather than just running the script without a primary input like the GEOID12B file, in my case.

**Comment by Kevin-GIS** [comment]
Hi @LowellMA-stormwater 

Thank you for the response and for posting your solution with installing the Coordinate Systems Data. Was the tool working successfully after installing that data?

**Comment by LowellMA-stormwater** [comment]
Yes, Kevin, this resolved the issue and I now have control points surveyed to within 19 mm using Collector from my iPad. Thanks for your work!

**Comment by Kevin-GIS** [comment]
Thank you @LowellMA-stormwater!

We will look into improving the tool's validation to check for the coordinate system data being installed or not.
